name: Mac Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: PATH=$PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include cmake -DCMAKE_BUILD_TYPE=Release ..
      env:
        WM_DOWNLOAD_EXTERNALS: 1
        HEADER_SEARCH_PATHS: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
        C_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
        CPLUS_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    - name: pack
      run: cpack
      working-directory: build
