name: Mac Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      env:
        WM_DOWNLOAD_EXTERNALS: 1
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    - name: pack
      run: cpack
      working-directory: build
