name: Mac Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: brew install boost
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      env:
        WM_DOWNLOAD_EXTERNALS: 0
        HEADER_SEARCH_PATHS: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
        C_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
        CPLUS_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build
    - name: pack
      run: cmake --build . --config Release --target package
      working-directory: build
    - uses: actions/upload-artifact@v1
      with:
        name: werckmeister-mac-${{ github.sha }}
        path: build/werckmeister-0.1.53-Darwin.sh
